---
global:
  image:
    # -- Overrides the Docker registry globally for all images
    registry: harbor.mustafar.lol

loki:
  image:
    # -- The Docker registry
    registry: harbor.mustafar.lol
    # -- Docker image repository
    repository: grafana/loki

  # Should authentication be enabled
  auth_enabled: false

read:
  # -- Number of replicas for the read
  replicas: 1
  persistence:
    # -- Size of persistent disk
    size: 2Gi
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: longhorn

write:
  # -- Number of replicas for the read
  replicas: 1
  persistence:
    # -- Size of persistent disk
    size: 2Gi
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: longhorn

gateway:
  ingress:
    enabled: true
    hosts:
    - host: loki.svc.mustafar.lol
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - loki.svc.mustafar.lol
      secretName: loki-gateway-tls