---
global:
  image:
    # -- Overrides the Docker registry globally for all images
    registry: harbor.mustafar.lol

loki:
  # Configures the readiness probe for all of the Loki pods
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 30
    timeoutSeconds: 1
  image:
    # -- The Docker registry
    registry: harbor.mustafar.lol
    # -- Docker image repository
    repository: grafana/loki

  # Should authentication be enabled
  auth_enabled: false

# Use either this ingress or the gateway, but not both at once.
# If you enable this, make sure to disable the gateway.
# You'll need to supply authn configuration for your ingress controller.
ingress:
  enabled: true
  hosts:
  - loki.svc.mustafar.lol
  # tls:
  #   - hosts:
  #     - loki.svc.mustafar.lol
  #     secretName: loki-distributed-tls

# Configuration for the gateway
gateway:
  # -- Specifies whether the gateway should be enabled
  enabled: false
