kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: service-cluster-loader
  namespace: fleet-local
spec:
  repo: https://github.com/rancherfederal/kubecon-fleet-stack.git
  branch: main  
  targets:
  - clusterName: local
  #! patch command: kubectl patch ClusterGroup -n fleet-local default --type=json -p='[{"op": "remove", "path": "/spec/selector/matchLabels/name"}]'

  paths:
  - "./gitops/clusters/harvester1/services"