cloudprovider: harvester
cloudCredentialSecretName: cattle-global-data:cc-q45sl
cluster:
  annotations: {}
  labels:
    environment: demo
    cluster_name: alpha
  name: rke2-harvester-demo-alpha
kubernetesVersion: v1.24.2+rke2r1
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false
nodepools:
- etcd: true
  controlplane: true
  worker: false
  displayName: control-plane-nodes
  name: control-plane-nodes
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/workloads
  networkType: dhcp
  imageName: default/image-4jz2k
  vmNamespace: default
  sshUser: ubuntu
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-nodes
  name: worker-nodes
  labels: {}
  taints: {}
  quantity: 3
  paused: false
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/workloads
  networkType: dhcp
  imageName: default/image-4jz2k
  vmNamespace: default
  sshUser: ubuntu
