kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: essentials
  namespace: fleet-default
spec:
  repo: https://git.mustafar.lol/gitea/kubecon-fleetstack.git
  branch: main

  targets:
  - clusterSelector:
      matchLabels:
        location: el8000

  paths:
  - "./gitops/apps/essentials"