kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: log-aggregator
  namespace: fleet-default
spec:
  repo: https://github.com/rancherfederal/kubecon-fleet-stack.git
  branch: main

  # To target specific clusters, uncomment this block
  targets:
  - clusterSelector:
      matchLabels:
        environment: services

  paths:
  - "./gitops/apps/logging/loki"