kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: monitoring
  namespace: fleet-default
spec:
  repo: https://git.mustafar.lol/gitea/kubecon-fleetstack.git
  branch: main

  # To target specific clusters, uncomment this block
  targets:
  - clusterSelector:
      matchLabels:
        environment: prod
  - clusterSelector:
      matchLabels:
        environment: services

  paths:
  - "./gitops/apps/monitoring"