kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: registry
  namespace: fleet-default
spec:
  repo: https://github.com/rancherfederal/kubecon-fleet-stack.git
  branch: main
  
  targets:
  - clusterSelector:
      matchLabels:
        environment: services
        cluster_name: shared

  paths:
  - "./gitops/apps/registry/"